## Gradient with AutoGrad
### Gradients are essential for Model Optimization
### Autograd package does all the computations for us
### We Just need to learn how autograd does this

In [2]:
import torch


In [3]:
x = torch.randn(3)
print('tensor', x)

tensor tensor([-0.2404,  0.1262, -0.8172])


In [4]:
# WE we want to calculate gradient of x, we must specify an argument
x = torch.randn(3, requires_grad = True)   #default its False
print(x)                                    
# Now whenever we do computations with this tensor, pytorch creates a Computational graph to trace back

tensor([ 0.5869, -0.5716,  0.5889], requires_grad=True)


In [5]:
y = x + 2         #This creates a computational graph with input x & 2, with additional '+' node
print(y)          # In backword pass it calculates gradient w.r.t input x i.e, dy/dx

tensor([2.5869, 1.4284, 2.5889], grad_fn=<AddBackward0>)


In [6]:
z = y*y*2
print(z)     # MulBackward

tensor([13.3843,  4.0808, 13.4046], grad_fn=<MulBackward0>)


In [7]:
z = z.mean()
print(z)     # MeanBackward

tensor(10.2899, grad_fn=<MeanBackward0>)


In [8]:
# Now to calculate gradient of z wrt input, We Must Call 'backward()'
z.backward()
# Then x gets a .grad attribute where gradients are stored
print(x.grad)

tensor([3.4492, 1.9046, 3.4518])


### Lets see when we dont specify the requires_grad argument

In [9]:
x = torch.randn(4)
print(x)

tensor([ 0.0513,  0.6298, -0.5112, -1.4634])


In [10]:
y = x + 2
print(y)

z = y*y*2
z = z.mean()
print(z)         # Here the tensors printed doesn't show the grad attribute

tensor([2.0513, 2.6298, 1.4888, 0.5366])
tensor(6.8141)


In [11]:
# Now if we call backward function, it will throw error
z.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [13]:
print(x.grad)

None


### In Background it creates a Backtorch Jaccobian Product to checkout the gradients J.v  = Partial derivatives * Gradient Vector = Final gradients 
### This is also called as Chain Rule

In [26]:
# So, in the case without argument, since z is Scalar value,
# So, for z with more than 1 value in a tensor
x = torch.randn(4, requires_grad = True)        # Will get error if this argument is not added for getting x.grad
y = x + 2

z = y*y*2
print(z)
# z.backward()    # if we are calling backword here, will get error, that graad can be implicitly created only for scalar outputs

tensor([ 9.1455, 10.3762,  7.0459,  3.8843], grad_fn=<MulBackward0>)


In [27]:
# So in such a case we have to give a gradient argument, create a some random vector of same size
v = torch.tensor([0.1, 1.0, 0.01, 1.01], dtype=torch.float32)
# Now pass this vector to backward function
z.backward(v)         # if input to backward is not Scalar, then we must multiply a vector'v', to get grad
print(x.grad)        

tensor([0.8554, 9.1109, 0.0751, 5.6302])
