In [1]:
import torch

In [2]:
my_tensor = torch.tensor([[1,2,3], [4,5,6]])
my_tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

### set d-type : float, int : 32 or 64

In [4]:
my_tensor = torch.tensor([[1,2,3], [4,5,6]], dtype = torch.float32)   
my_tensor 

tensor([[1., 2., 3.],
        [4., 5., 6.]])

### set device on which tensor to run: cuda/gpu/cpu

In [ ]:
my_tensor = torch.tensor([[1,2,3], [4,5,6]], dtype = torch.float32, device = 'cpu')    #cpu is default, can have cuda if available
my_tensor

### can have additional arguments

In [9]:
device = "cuda" if torch.cuda.is_available() else "cpu"
my_tensor = torch.tensor([[1,2,3], [4,5,6]], dtype = torch.float32, 
                         device = device, requires_grad = True)
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)

In [12]:
# check attributes of tensor
print(my_tensor)
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape)
print(my_tensor.requires_grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)
torch.float32
cpu
torch.Size([2, 3])
True


### Other Common Initialization methods

In [14]:
x = torch.empty(size = (3,3))
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [15]:
x = torch.zeros((3,3))
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [17]:
x = torch.rand(3,3)
x

tensor([[0.8500, 0.4518, 0.9532],
        [0.7765, 0.3738, 0.3821],
        [0.8783, 0.7389, 0.7894]])

In [18]:
x = torch.ones(3,3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [19]:
x = torch.eye(5,5)   # Identity matrix
x

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [21]:
x = torch.arange(start = 0, end = 5, step =1)    # Creating list or array in range
x

tensor([0, 1, 2, 3, 4])

In [22]:
x = torch.linspace(start = 0.1, end = 1, steps = 10)
x

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

In [23]:
x = torch.empty(size=(1,5)).normal_(mean=0, std=1)  
#this will initialze the data of size 1*5, those values are normally distributed with mean of 0 and standard deviation of 1
x

tensor([[-0.0337, -0.5479, -0.8162,  0.2511,  0.2808]])

In [24]:
#For uniform distribution
x = torch.empty(size=(1,5)).uniform_(0,1)    #here specifying lower and upper of uniform distribution
x

tensor([[0.7194, 0.4068, 0.7169, 0.8511, 0.9609]])

In [25]:
x = torch.diag(torch.ones(3))    #Diagonal / Identity matrix
x

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

### How to initialize and convert tensors to other types (int,  float, double)

In [26]:
tensor = torch.arange(4)
tensor

tensor([0, 1, 2, 3])

In [32]:
print(tensor.bool())
print(tensor.short())
print(tensor.long())
print(tensor.half())
print(tensor.float())
print(tensor.double())

tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)


### Array to Tensor Conversion and vice versa

In [33]:
import numpy as np

In [41]:
np_array = np.zeros((5,5))
np_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [36]:
tensor = torch.from_numpy(np_array)
tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)

In [38]:
np_array_back = tensor.numpy()
np_array_back

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Tensor Math & Comparison Operations

In [42]:
x = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])

In [43]:
# Addition
z1 = torch.empty(3)
torch.add(x,y, out = z1)

tensor([10., 10., 10.])

In [45]:
#OR
z2 = torch.add(x,y)
z2 = x + y
z2

tensor([10, 10, 10])

In [46]:
#Subtraction
z = x - y
z

tensor([-8, -6, -4])

In [47]:
#Division
z = torch.true_divide(x,y)
z

tensor([0.1111, 0.2500, 0.4286])

In [50]:
## In place operations
t = torch.zeros(3)
t.add_(x)

# OR
#t += x
#t

tensor([2., 4., 6.])

In [52]:
##Exponetiation
z = x.pow(2)
z

#OR
z = x ** 2
z

tensor([1, 4, 9])

In [54]:
## Simple comparison
z = x > 0
z
z = x < 0
z

tensor([False, False, False])

In [57]:
## Matrix Multiplication
x1 = torch.rand((2,5))
x2 = torch.rand((5,3))

x3 = torch.mm(x1, x2)      # 2*5  *  5*3 == 2*3 output
x3

#OR
x3 = x1.mm(x2)
x3

tensor([[0.6936, 1.9989, 0.7322],
        [0.5080, 1.8885, 0.6080]])

In [62]:
## MAtrix Exponentiation
matrix_exp = torch.rand(5,5)
print(matrix_exp)
matrix_exp.matrix_power(3)

tensor([[0.1447, 0.1461, 0.9445, 0.0434, 0.2359],
        [0.9543, 0.1525, 0.7178, 0.3530, 0.1096],
        [0.2943, 0.0555, 0.6920, 0.9497, 0.5726],
        [0.0026, 0.9951, 0.5287, 0.9663, 0.9453],
        [0.4821, 0.6975, 0.5233, 0.0351, 0.8974]])


tensor([[1.0855, 1.7734, 2.4330, 2.1211, 2.4672],
        [1.7222, 2.1466, 3.3434, 3.0319, 3.2356],
        [2.8350, 3.3249, 4.5272, 3.6881, 4.4373],
        [3.6138, 3.9473, 6.3160, 4.5228, 5.4342],
        [2.1927, 2.1777, 4.2547, 2.9273, 3.4176]])

In [63]:
## element wise multiplication
z = x * y
z

tensor([ 9, 16, 21])

In [64]:
## dot product
z = torch.dot(x,y)
z

tensor(46)

In [69]:
## Batch Matrix Multiplication(bmm)
batch = 32
n = 10
m = 20
p = 30

tensor1 = torch.rand((batch, n, m))     # for 2 dimensional, we can do normal mm , here its 3D
print(tensor1.shape)
tensor1

torch.Size([32, 10, 20])


tensor([[[0.7534, 0.2992, 0.7247,  ..., 0.7294, 0.5020, 0.8619],
         [0.3052, 0.6099, 0.4637,  ..., 0.4866, 0.1303, 0.5059],
         [0.6005, 0.5723, 0.4249,  ..., 0.3213, 0.6917, 0.9548],
         ...,
         [0.1664, 0.1037, 0.5333,  ..., 0.0016, 0.5641, 0.2641],
         [0.0145, 0.9254, 0.6716,  ..., 0.8198, 0.4230, 0.8215],
         [0.2592, 0.3769, 0.1593,  ..., 0.4423, 0.0628, 0.6258]],

        [[0.2688, 0.7028, 0.0769,  ..., 0.4116, 0.7722, 0.6443],
         [0.4010, 0.2357, 0.9200,  ..., 0.0039, 0.9274, 0.4588],
         [0.9494, 0.9021, 0.5990,  ..., 0.9016, 0.3443, 0.8555],
         ...,
         [0.4785, 0.8273, 0.1163,  ..., 0.3213, 0.7960, 0.5909],
         [0.9625, 0.8659, 0.7080,  ..., 0.4210, 0.5006, 0.8448],
         [0.6054, 0.9864, 0.2880,  ..., 0.2778, 0.2315, 0.1516]],

        [[0.9318, 0.6888, 0.1842,  ..., 0.1458, 0.1543, 0.5499],
         [0.4427, 0.6000, 0.5014,  ..., 0.7568, 0.1265, 0.2681],
         [0.6341, 0.0520, 0.1481,  ..., 0.9131, 0.4110, 0.

In [71]:
tensor2 = torch.rand((batch, m, p))
print(tensor2.shape)
tensor2

torch.Size([32, 20, 30])


tensor([[[0.4830, 0.1019, 0.3422,  ..., 0.6492, 0.3191, 0.7804],
         [0.1753, 0.6931, 0.3977,  ..., 0.8794, 0.6572, 0.5111],
         [0.4146, 0.4786, 0.4168,  ..., 0.8883, 0.3178, 0.6436],
         ...,
         [0.6853, 0.7649, 0.3734,  ..., 0.9047, 0.2575, 0.4791],
         [0.1243, 0.1455, 0.9276,  ..., 0.9486, 0.6564, 0.3687],
         [0.0838, 0.3151, 0.4448,  ..., 0.7346, 0.7872, 0.0668]],

        [[0.9710, 0.2441, 0.7558,  ..., 0.9496, 0.3586, 0.1638],
         [0.4552, 0.8776, 0.2353,  ..., 0.0361, 0.2081, 0.0145],
         [0.8788, 0.8517, 0.2486,  ..., 0.3508, 0.7568, 0.2790],
         ...,
         [0.0672, 0.3536, 0.6378,  ..., 0.2226, 0.0269, 0.6559],
         [0.7044, 0.5598, 0.7632,  ..., 0.6970, 0.8378, 0.7008],
         [0.6606, 0.2737, 0.5996,  ..., 0.1494, 0.9514, 0.9549]],

        [[0.9493, 0.1471, 0.5958,  ..., 0.7844, 0.1623, 0.6623],
         [0.2110, 0.4863, 0.6069,  ..., 0.1132, 0.9456, 0.2943],
         [0.7193, 0.9187, 0.8934,  ..., 0.0174, 0.9229, 0.

In [74]:
out_bmm = torch.bmm(tensor1,tensor2)
print(out_bmm.shape)
out_bmm

torch.Size([32, 10, 30])


tensor([[[5.0275, 5.5913, 5.0034,  ..., 5.9040, 5.9302, 6.4760],
         [4.6534, 6.1781, 5.0402,  ..., 4.8914, 4.7357, 5.9697],
         [3.4789, 4.9157, 3.8970,  ..., 4.9178, 4.9282, 4.9073],
         ...,
         [3.2777, 3.4235, 4.1918,  ..., 3.6519, 3.5850, 4.3287],
         [5.3072, 6.9218, 5.9643,  ..., 6.6236, 6.5446, 7.1023],
         [4.5977, 6.4635, 4.6398,  ..., 5.4170, 5.7692, 6.1579]],

        [[5.1503, 5.5038, 4.6471,  ..., 5.0456, 4.8852, 4.1915],
         [6.1639, 5.5813, 5.0572,  ..., 5.2987, 5.2640, 4.1689],
         [6.3369, 7.0312, 6.1478,  ..., 6.0822, 6.3441, 5.1830],
         ...,
         [4.6979, 4.9532, 4.0248,  ..., 4.1231, 4.2343, 3.4138],
         [6.0472, 5.4364, 5.2844,  ..., 6.2996, 5.3798, 4.7146],
         [3.4463, 3.5853, 3.3366,  ..., 3.2722, 3.5641, 2.4342]],

        [[6.0686, 4.9056, 4.7619,  ..., 5.0771, 5.6501, 6.1401],
         [5.6818, 5.1426, 5.1007,  ..., 4.6474, 5.5193, 5.4459],
         [6.0012, 4.7447, 4.5983,  ..., 5.5633, 4.8091, 5.

In [75]:
## Examples of Broadcasting
#i.e, expanding dimensions of matrix to match with other matrix dimension
x1 = torch.rand((5,5))
x2 = torch.rand((1,5))

print(x1)
print(x2)
z = x1 - x2      # x2 vector of shape 1*5, is subtracted from each row of x1
z

tensor([[0.2221, 0.5185, 0.6679, 0.8497, 0.8395],
        [0.3690, 0.5183, 0.7987, 0.5676, 0.6073],
        [0.2562, 0.9713, 0.1964, 0.9415, 0.5876],
        [0.1959, 0.5563, 0.3718, 0.6963, 0.9644],
        [0.1196, 0.7275, 0.4181, 0.4122, 0.2153]])
tensor([[0.0343, 0.7335, 0.3389, 0.9487, 0.8788]])


tensor([[ 0.1878, -0.2150,  0.3291, -0.0990, -0.0393],
        [ 0.3346, -0.2152,  0.4599, -0.3812, -0.2715],
        [ 0.2218,  0.2378, -0.1424, -0.0073, -0.2912],
        [ 0.1616, -0.1771,  0.0329, -0.2524,  0.0855],
        [ 0.0853, -0.0059,  0.0792, -0.5365, -0.6635]])

In [77]:
z = x1 ** x2
z

tensor([[0.9496, 0.6177, 0.8722, 0.8568, 0.8575],
        [0.9663, 0.6175, 0.9267, 0.5843, 0.6451],
        [0.9543, 0.9789, 0.5761, 0.9444, 0.6267],
        [0.9456, 0.6505, 0.7151, 0.7093, 0.9686],
        [0.9297, 0.7919, 0.7442, 0.4314, 0.2593]])

In [86]:
## Other tensor operstions
sum_x = torch.sum(x, dim=0)
print('sum_x',sum_x)
values, indices = torch.max(x, dim=0)   #or : x.max(dim=0) instead of torch.max and other operations with torch.
values, indices = torch.min(x, dim=0)
abs_x = torch.abs(x)
print('absolute value',abs_x)
z = torch.argmax(x, dim=0)
z = torch.argmin(x, dim=0)
mean_x = torch.mean(x.float(), dim=0)   # For mean, we need float values
print('mean ', mean_x)
z = torch.eq(x,y)
print('check equal', z)

sum_x tensor(6)
absolute value tensor([1, 2, 3])
mean  tensor(2.)
check equal tensor([False, False, False])


In [88]:
sorted_y, indices = torch.sort(y, dim=0, descending = False)
print('sorted y', sorted_y)

sorted y tensor([7, 8, 9])


In [90]:
z = torch.clamp(x, min=0, max=10)   # all elements of x less than 0 are set to 0 and any value greater than 10 set to 10
#Its exactly like a ReLU function
z

tensor([1, 2, 3])

In [91]:
x = torch.tensor([1,0,1,1,1], dtype = torch.bool)
#check any of these values are true
z = torch.any(x)
z = torch.all(x)    # All values need to 1, not a single value should be false
z

tensor(False)

### Tensor Indexing

In [105]:
batch_size = 10
features = 25
x = torch.rand((batch_size, features))   #Initialize some random input
print(x[0])
print(x.size())
print('shape of x[0]', x[0].shape)    # x[0, :]
print('first feature of all inputs', x[:, 0])
print(x[:, 0])


tensor([0.5114, 0.9230, 0.2733, 0.7984, 0.8376, 0.4497, 0.9692, 0.7962, 0.1751,
        0.2785, 0.3533, 0.8933, 0.0768, 0.3012, 0.0996, 0.2850, 0.6582, 0.5518,
        0.6256, 0.8822, 0.3416, 0.8392, 0.8233, 0.7597, 0.0475])
torch.Size([10, 25])
shape of x[0] torch.Size([25])
first feature of all inputs tensor([0.5114, 0.0922, 0.8864, 0.8406, 0.7672, 0.4005, 0.5041, 0.5311, 0.2296,
        0.3802])
tensor([0.5114, 0.0922, 0.8864, 0.8406, 0.7672, 0.4005, 0.5041, 0.5311, 0.2296,
        0.3802])


In [106]:
print('what is x: ',x)

what is x:  tensor([[0.5114, 0.9230, 0.2733, 0.7984, 0.8376, 0.4497, 0.9692, 0.7962, 0.1751,
         0.2785, 0.3533, 0.8933, 0.0768, 0.3012, 0.0996, 0.2850, 0.6582, 0.5518,
         0.6256, 0.8822, 0.3416, 0.8392, 0.8233, 0.7597, 0.0475],
        [0.0922, 0.9253, 0.6790, 0.9682, 0.7550, 0.0486, 0.5873, 0.6298, 0.8087,
         0.9305, 0.1607, 0.0230, 0.2951, 0.9333, 0.7299, 0.4365, 0.9324, 0.6584,
         0.1186, 0.5617, 0.4498, 0.2450, 0.0276, 0.6454, 0.9139],
        [0.8864, 0.9024, 0.0259, 0.6211, 0.9970, 0.0697, 0.5441, 0.7162, 0.4187,
         0.9334, 0.7935, 0.6745, 0.1219, 0.8657, 0.6770, 0.2898, 0.1627, 0.7993,
         0.2377, 0.5386, 0.1774, 0.4110, 0.9746, 0.0593, 0.9666],
        [0.8406, 0.0030, 0.5117, 0.1339, 0.1398, 0.3006, 0.0852, 0.2031, 0.3624,
         0.5800, 0.8771, 0.7649, 0.3076, 0.6187, 0.0272, 0.0717, 0.2996, 0.1654,
         0.5261, 0.3816, 0.4536, 0.4561, 0.7804, 0.5178, 0.0269],
        [0.7672, 0.6230, 0.7057, 0.3803, 0.6335, 0.5552, 0.9560, 0.7138, 0.8

In [108]:
# get 3rd example in the batch and its 10 features
x[2, 0:10]    #0:10 : will create a list

tensor([0.8864, 0.9024, 0.0259, 0.6211, 0.9970, 0.0697, 0.5441, 0.7162, 0.4187,
        0.9334])

In [111]:
#to assign a tensor
x[0,0] = 100
x

tensor([[1.0000e+02, 9.2295e-01, 2.7327e-01, 7.9843e-01, 8.3757e-01, 4.4972e-01,
         9.6917e-01, 7.9616e-01, 1.7509e-01, 2.7854e-01, 3.5326e-01, 8.9329e-01,
         7.6791e-02, 3.0118e-01, 9.9629e-02, 2.8501e-01, 6.5820e-01, 5.5182e-01,
         6.2563e-01, 8.8217e-01, 3.4159e-01, 8.3918e-01, 8.2326e-01, 7.5968e-01,
         4.7519e-02],
        [9.2218e-02, 9.2532e-01, 6.7904e-01, 9.6815e-01, 7.5496e-01, 4.8636e-02,
         5.8725e-01, 6.2983e-01, 8.0865e-01, 9.3053e-01, 1.6070e-01, 2.3022e-02,
         2.9511e-01, 9.3328e-01, 7.2995e-01, 4.3648e-01, 9.3241e-01, 6.5842e-01,
         1.1857e-01, 5.6167e-01, 4.4977e-01, 2.4503e-01, 2.7597e-02, 6.4544e-01,
         9.1392e-01],
        [8.8644e-01, 9.0239e-01, 2.5907e-02, 6.2114e-01, 9.9700e-01, 6.9716e-02,
         5.4411e-01, 7.1623e-01, 4.1875e-01, 9.3336e-01, 7.9352e-01, 6.7448e-01,
         1.2186e-01, 8.6572e-01, 6.7695e-01, 2.8982e-01, 1.6266e-01, 7.9927e-01,
         2.3769e-01, 5.3859e-01, 1.7738e-01, 4.1101e-01, 9.7463e-

In [112]:
## Fancy Indexing

x = torch.arange(10)
indices = [2,3,8]           
print(x[indices])

tensor([2, 3, 8])


In [116]:
x = torch.rand((3,5))
print('what is x :', x)
rows = torch.tensor([1,0])
cols = torch.tensor([4,0])
print(x[rows,cols])
print(x[rows,cols].shape)

what is x : tensor([[0.9083, 0.9799, 0.7053, 0.8198, 0.3890],
        [0.5724, 0.6772, 0.1321, 0.4391, 0.5801],
        [0.0954, 0.2949, 0.9996, 0.5076, 0.9109]])
tensor([0.5801, 0.9083])
torch.Size([2])


In [121]:
## More advanced indexing
x = torch.arange(10)
print(x)
#pick out elements <2 and >8
print(x[(x < 2)| (x > 8)])    #OR
print(x[(x < 2) & (x > 8)])   #AND
print(x[x.remainder(2) == 0]) #even or module=0

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 1, 9])
tensor([], dtype=torch.int64)
tensor([0, 2, 4, 6, 8])


In [124]:
## More operations
x = torch.arange(10)
print(x)
print(torch.where(x > 5, x, x * 2))  # if x >5, set the value to x else return x*2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])


In [125]:
torch.tensor([0,0,1,2,2,3,4]).unique()

tensor([0, 1, 2, 3, 4])

In [126]:
print(x.ndimension())

1


In [128]:
print(x.numel())   #to count no. of elements in x

10


### Tensor Reshaping

In [131]:
x = torch.arange(9)

#convert to 3*3 matrix
x_3x3 = x.view(3,3)   # act on contineous block of memory
x_3x3
#OR
x_3x3 = x.reshape(3,3)  #contineous memory block not needed, safe to use but computationally difficult
x_3x3

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [137]:
y = x_3x3.t()     #transpose
#[0,3,6,1,4,7,2,5,8]   : for 1 element jump in y, there is 3 element jump in x
y
# y.view(9)    #trows error as not contigeous
y.contiguous().view(9)

tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])

In [148]:
x1 = torch.rand((2,5))
x2 = torch.rand((2,5))
print(torch.cat((x1,x2)))
print(torch.cat((x1,x2), dim=0))
(torch.cat((x1,x2), dim=0).shape)
print(torch.cat((x1,x2), dim=1))
print(torch.cat((x1,x2), dim=1).shape)

tensor([[0.9889, 0.5290, 0.6387, 0.2929, 0.3761],
        [0.1153, 0.3955, 0.5157, 0.3675, 0.7052],
        [0.1658, 0.0671, 0.2024, 0.7210, 0.9577],
        [0.4665, 0.0309, 0.6798, 0.8408, 0.1929]])
tensor([[0.9889, 0.5290, 0.6387, 0.2929, 0.3761],
        [0.1153, 0.3955, 0.5157, 0.3675, 0.7052],
        [0.1658, 0.0671, 0.2024, 0.7210, 0.9577],
        [0.4665, 0.0309, 0.6798, 0.8408, 0.1929]])
tensor([[0.9889, 0.5290, 0.6387, 0.2929, 0.3761, 0.1658, 0.0671, 0.2024, 0.7210,
         0.9577],
        [0.1153, 0.3955, 0.5157, 0.3675, 0.7052, 0.4665, 0.0309, 0.6798, 0.8408,
         0.1929]])
torch.Size([2, 10])


In [150]:
#Unroll x1
z = x1.view(-1)
print(z)
z.shape

torch.Size([10])

In [152]:
#Complex
batch = 64
x = torch.rand(batch, 2,5)  #(dim0 = batch, dim1=2, dim2=5)
z = x.view(batch, -1)
z.shape

torch.Size([64, 10])

In [155]:
#switch axis(2,5 to 5,2)

z = x.permute(0, 2, 1)    #(dim0, dim2, dim1)
z                         #like transpose
z.shape

torch.Size([64, 5, 2])

In [160]:
x = torch.arange(10)
print(x)
print(x.unsqueeze(0))    #1*10 vector
print(x.unsqueeze(0).shape)     
print(x.unsqueeze(1).shape)   #10*1 vectro

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
torch.Size([1, 10])
torch.Size([10, 1])


In [163]:
x = torch.arange(10).unsqueeze(0).unsqueeze(1)    #1*1*10
x
x.shape

z = x.squeeze(1)
print(z.shape)

torch.Size([1, 10])
